version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "127.0.0.1:8080:80"
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile